from krtech.decorators import page
from krtech.elements.base_element import BaseElement
from krtech.elements.input import Input
from krtech.elements.checkbox import Checkbox
from krtech.elements.link import Link
from krtech.elements.list import List
from krtech.elements.select import Select
from krtech.pages.base_page import BasePage
from selenium.webdriver.common.by import By
